package alvin.bef.framework.base.exception;

/**
 * Each SOAP Fault gets an error code from this list.
 */
public enum SoapErrorCode {
   API_DISABLED,
   CANNOT_DELETE,
   CANNOT_SCHEDULE,
   CREDIT_CARD_PROCESSING_FAILURE,
   DUPLICATE_VALUE,
   INVALID_FIELD,
   INVALID_LOGIN,
   INVALID_SESSION,
   INVALID_TYPE,
   INVALID_ID,
   INVALID_VALUE,
   INVALID_VERSION,
   LOCK_COMPETITION,
   MALFORMED_QUERY,
   MAX_RECORDS_EXCEEDED,
   MISSING_REQUIRED_VALUE,
   NO_PERMISSION,
   UNKNOWN_ERROR,
   TRANSACTION_FAILED,
   INVALID_TEMPLATE,
   ACCOUNTING_PERIOD_CLOSED,
   BATCH_FAIL_ERROR,
   PDF_QUERY_ERROR,
   REQUEST_EXCEEDED_LIMIT,
   REQUEST_REJECTED,
   TEMPORARY_ERROR,
   TRANSACTION_TERMINATED,
   TRANSACTION_TIMEOUT,
   REQUEST_EXCEEDED_RATE
   ;
}
